name: K6 Extension Workflow - kafka
on: 
  workflow_dispatch:
    inputs:
      VUS:
        required: true
        type: string
      DURATION:
        required: true
        type: string
      BROKERS:
        required: true
        type: string
      USER_SASL:
        required: false
        type: string
      PASS_SASL:
        required: false
        type: string
      SCRIPT:
        required: true
        type: string

jobs:
  k6_local_test:
    name: k6 counter extension run
    runs-on: self-hosted
    container: docker://golang:1.21-alpine

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install xk6
        run: go install go.k6.io/xk6/cmd/xk6@latest

      - name: Build xk6-counter binary
        run: xk6 build --with github.com/mostafa/xk6-kafka@latest

      - name: Run k6 extension test
        run: ./k6 run --vus ${{ inputs.VUS }} --duration ${{ inputs.DURATION }} -e BROKERS=${{ inputs.BROKERS }} -e USER_SASL=${{ inputs.USER_SASL }} -e PASS_SASL=${{ inputs.PASS_SASL }} ${{ inputs.SCRIPT }}

